services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer/cache
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_database
      DB_USERNAME: laravel_user
      DB_PASSWORD: super_secret_password
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_mysql_db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_database
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: super_secret_password
      MYSQL_ROOT_PASSWORD: root_password_to_access_db
    restart: always

volumes:
  mysql-data:
  composer-cache:
